import {styles,palettes,renderSVG} from './generator.js';
import {partsProvider} from './provider.js';
const $=id=>document.getElementById(id);let candidates=[],selected=0;
styles.forEach((name,i)=>$('style').add(new Option(name+'系',i)));palettes.forEach((p,i)=>$('palette').add(new Option(p.name,i)));
function note(){$('style-note').textContent='選んだテイストを、線の太さ・配色・質感で表現します。';}note();
function draw(){$('candidates').replaceChildren();candidates.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.className='candidate'+(i===selected?' selected':'');b.setAttribute('aria-pressed',String(i===selected));b.setAttribute('aria-label',`候補 ${i+1}：${palettes[c.palette].name}`);b.innerHTML=renderSVG(c);const caption=document.createElement('span');caption.textContent=`${i===selected?'✓ ':''}候補 ${i+1}`;b.append(caption);b.onclick=()=>{selected=i;draw();};$('candidates').append(b);});const c=candidates[selected];$('palette').value=c.palette;$('pattern').value=c.pattern;$('lettering').value=c.lettering;$('header-preview').innerHTML=renderSVG(c,'header');$('avatar-preview').innerHTML=renderSVG(c);$('preview-name').textContent=c.name||'あなたのアカウント';$('preview-bio').textContent=c.profile;}
async function generate(){const button=$('generate');button.disabled=true;try{candidates=await partsProvider.generate({name:$('name').value.trim(),profile:$('profile').value.trim(),audience:$('audience').value,style:Number($('style').value),motif:$('motif').value});selected=0;draw();$('status').textContent='4つの候補ができました。好きな候補を選んでください。';}catch{$('status').textContent='候補を作れませんでした。もう一度お試しください。';}finally{button.disabled=false;}}
$('form').addEventListener('submit',e=>{e.preventDefault();generate();});$('style').onchange=note;
for(const key of ['palette','pattern','lettering'])$(key).onchange=()=>{candidates[selected][key]=key==='palette'?Number($(key).value):$(key).value;draw();};
async function download(kind){const button=$(kind==='icon'?'save-icon':'save-header');button.disabled=true;let url;try{url=URL.createObjectURL(new Blob([renderSVG(candidates[selected],kind)],{type:'image/svg+xml'}));const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=kind==='icon'?400:1500;canvas.height=kind==='icon'?400:500;canvas.getContext('2d').drawImage(img,0,0);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('export');const fileURL=URL.createObjectURL(blob);const a=document.createElement('a');a.href=fileURL;a.download=`x-${kind}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(fileURL),10000);$('status').textContent=`${kind==='icon'?'アイコン':'ヘッダー'}のPNGを保存しました。`;}catch{$('status').textContent='画像を保存できませんでした。別のブラウザでお試しください。';}finally{if(url)URL.revokeObjectURL(url);button.disabled=false;}}
$('save-icon').onclick=()=>download('icon');$('save-header').onclick=()=>download('header');generate();
